runtime: python39

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  OPENAI_API_KEY: "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"  # Store API key as an environment variable

instance_class: F2